apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: strajkers
  description: The infra business unit
spec:
  type: business-unit
  profile:
    displayName: Strajkers
    email: infrastructure@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  parent: ops
  children: [backstage, other]
  members: [jdoe]
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: strajk-bowling
  annotations:
    github.com/project-slug: meganide/strajk-bowling
spec:
  type: other
  lifecycle: unknown
  owner: strajkers
