apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: strajk-bowling
  annotations:
    github.com/project-slug: meganide/strajk-bowling
spec:
  type: other
  lifecycle: unknown
  owner: guests
